version: '3.7'
services:
  proxy:
    image: "envoyproxy/envoy:contrib-v1.27.1"
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./traffic.so:/lib/traffic.so
    environment:
      - GODEBUG=cgocheck=0