version: '3.7'
services:
  proxy:
    image: "envoyproxy/envoy:contrib-v1.27.1"
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./traffic.so:/lib/traffic.so
    environment:
      - GODEBUG=cgocheck=0
    networks:
      - default
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "8080:8080"
    networks:
      - default
networks:
  default:
    driver: bridge
